name: Fly Deploy
on:
  workflow_dispatch:
    inputs:
      branches:
        default: master
  push:
    branches:
      - master    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
    
      - name: Write fly.toml from repository variable
        run: echo "$FLY_TOML" > fly.toml
        env:
          FLY_TOML: ${{ vars.FLY_TOML }}
          
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

